config/routes.rb
Rails.application.routes.draw do
  
  root to:'static_pages#home', as: 'home'

  resources :gossips
  resources :users
  resources :cities, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'static_pages/team', to: 'static_pages#team'
  get 'static_pages/contact', to: 'static_pages#contact'
  get 'welcome/:name', to: 'static_pages#welcome'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :tags_assignments
  has_many :tags, through: :tag_assignments
  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_assignments, dependent: :destroy
  has_many :gossips, through: :tag_assignments
end

app/models/tag_assignment.rb
class TagAssignment < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email,
    presence: true,
    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    # Look up the current user based on user_id in the session cookie:
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'Vous devez être connecté pour voir cette page.' if current_user.nil?
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @users = User.where(city_id: @city.id)
    @gossips = Gossip.where(user_id: @users)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :show]

  def new
    @gossip = Gossip.new
  end

  def index
    @gossips = Gossip.all
  end

  def create
    @gossip = Gossip.new('title' => params[:title], 'content' => params[:content], user_id: current_user[:id])
    if @gossip.save
      flash[:notice] = "Potin enregistré !"
      redirect_to home_path
    else
      flash[:alert] = "Erreur, le potin n'a pas été enregistré"
      puts @gossip.errors.messages
      render 'new'
    end
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user.id
      @gossip = Gossip.find(params[:id])
    else
      redirect_to(gossip_path(params[:id]), notice: "Tu dois en être l'auteur du potin !")
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user.id
      @gossip = Gossip.find(params[:id])
      if @gossip.update(title: params[:title], content: params[:content])
        redirect_to(home_path, notice: 'Gossip modifié!')
      else
        render :edit
      end
    else
     redirect_to(gossip_path(params[:id]), notice: "Tu dois en être l'auteur du potin !")
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user.id
      @gossip = Gossip.find(params[:id])
      @gossip.destroy
      redirect_to(home_path, notice: 'Gossip supprimé!')
    else
      redirect_to(gossip_path(params[:id]), notice: "Tu dois en être l'auteur du potin !")
    end
  end

  def authenticate_user
    unless current_user
      redirect_to(new_session_path, notice: 'Vous devez être connecté')
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    puts user
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: "Connecté!"
    else
      flash.now[:alert] = "Email / Mot de passe invalide"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: "Logged out!"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def welcome
    @name = params[:name]
  end

  def gossip
    @gossip_id = params[:gossip_id]
  end

  def author
    @author_id = params[:author_id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(
      email: params[:email],
      password: params[:password],
      city_id: 1,
      description: params[:description],
      age: params[:age],
      first_name: params[:first_name],
      last_name: params[:last_name]
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Utilisateur enregistré !"
      redirect_to home_path
    else
      flash[:alert] = "Erreur dans l'inscription"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<h2 style="margin-bottom: 2rem;">Page de la ville <%= @city.name %></h2>
<% @gossips.each do |gossip| %>
  <div class="card" style="width : 60vh; margin-bottom : 10px;">
    <div class="card-body">
      <h5 class="card-title"><%= gossip.title %> </h5>
      <p class="card-text"><%= gossip.content %> </p>
    </div>
  </div>
<% end %>

app/views/gossips/edit.html.erb
<h2 style="margin-bottom : 5rem">Modifier un potin (potin n°<%= @gossip.id %>) 
</h2>

<%= form_tag url_for(action: 'update'), method: "patch" do %>
  <%= label_tag 'Titre' %>
  <%= text_field_tag 'title', params[:title], class: "form-control", placeholder: @gossip.title, autocomplete: 'off' %>
  <br />
  <br />
  <%= label_tag 'Contenu' %>
  <%= text_area_tag 'content', params[:content], class: "form-control", placeholder: @gossip.content, autocomplete: 'off' %>
  <br />
  <br />
  <%= submit_tag "Modifier le potin", class: "btn btn-primary" %>  
<% end %>
 <div style="padding-top: 2rem;"><%= link_to "Supprimer le potin", gossip_path(@gossip.id), class: "btn btn-danger", method: "delete" %></div>

app/views/gossips/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <%= label_tag 'Titre' %>
  <%= text_field_tag 'title', @title, class: "form-control" %>
  <br />
  <br />
  <%= label_tag 'Contenu' %>
  <%= text_area_tag 'content', @content, class: "form-control" %>
  <br />
  <br />
  <%= submit_tag "Créer potin !", class: "btn btn-primary" %> 
<% end %>

<% if @gossip.errors.any? %>
  <p style="padding-top: 2rem;">Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= flash[:alert] = message %></li>
    <% end %>
  </ul>
<% end %>

app/views/gossips/show.html.erb
<h2 style="margin-bottom: 50px;">Potin n° <%= @gossip.id %> </h2>
 

<div>
  <h5>Titre :</h5>
  <p><%= @gossip.title %> </p>
  <h5>Contenu :</h5>
  <p> <%= @gossip.content %>  </p>
  <h5>L'auteur :</h5>
  <p><%= @gossip.user.first_name %><%= @gossip.user.last_name %> </p>
  <h5>Ville de l'auteur :</h5>
  <p> <%= @gossip.user.city.name %>  </p>
</div>


<div>
  <p><%= link_to "En savoir plus sur l'auteur", user_path(@gossip.user.id)%></p>
  <p class="lead mt-3 mb-4 ml-3 text-center"><%= link_to "Retour à l'accueil", home_path, :class => "btn btn-secondary" %></p>
  <p class="lead mt-3 mb-4 ml-3 text-center"><%= link_to "Editer", edit_gossip_path, :class => "btn btn-warning" %></p>
 
</div>

app/views/static_pages/author.html.erb
<h2 style="margin-bottom: 2rem;">L'auteur</h2>
 

<div>
  <h5>Prénom :</h5>
  <p><%= User.find(@author_id).first_name %> </p>
  <h5>Nom :</h5>
  <p><%= User.find(@author_id).last_name %> </p>
  <h5>Description :</h5>
   <p><%= User.find(@author_id).description %> </p>
  <h5>Email :</h5>
  <p><%= User.find(@author_id).email %> </p>
  <h5>Age :</h5>
  <p> <%= User.find(@author_id).age %>  </p>
  <h5>Ville :</h5>
  <p> <%= User.find(@author_id).city.name %>  </p>
</div>

app/views/static_pages/contact.html.erb
<h1>Page contact!</h1>
<p>Only fans bientôt</p>

app/views/static_pages/gossip.html.erb
<h2 style="margin-bottom: 50px;">Potin n° <%= @gossip_id %> </h2>
 

<div>
  <h5>Prénom :</h5>
  <p><%= Gossip.find(@gossip_id).user.first_name %> </p>
  <h5>Nom :</h5>
  <p><%= Gossip.find(@gossip_id).user.last_name %> </p>
  <h5>Titre :</h5>
  <p><%= Gossip.find(@gossip_id).title %> </p>
  <h5>Contenu :</h5>
  <p> <%= Gossip.find(@gossip_id).content %>  </p>
  <h5>Crée le :</h5>
  <p> <%= Gossip.find(@gossip_id).created_at %>  </p>
</div>


<div>
<p><%= link_to "En savoir plus sur l'auteur", author_path(Gossip.find(@gossip_id).user.id)%></p>
</div>

app/views/static_pages/home.html.erb
<h1 style="margin-bottom: 2rem">Bienvenue sur The Gossip Project</h1>
<p>Le meilleur réseau social pour moussaillons !</p>

<br>
<h4>Les potins !</h4>
<br>
<% Gossip.count.times do |i| %>

  <div class="card" style="width : 60vh; margin-bottom : 10px;">
    <div class="card-body">
      <h5 class="card-title"><%= Gossip.find(i+1).user.first_name %> </h5>
      <p class="card-text"><%= Gossip.find(i+1).title %> </p>  
      <%= link_to "Voir plus", gossip_path(Gossip.find(i + 1).id), class: "card-text"%>  
    </div>
  </div>
  
<% end %>

app/views/static_pages/team.html.erb
<h1>La Team !</h1>
<p>Jean Michel tout seul :)</p>

app/views/static_pages/welcome.html.erb
<h1>Welcome <%= @name %></h1>
<p>Ouais cette page est dynamique !</p>

app/views/users/new.html.erb
<h2>Créez un compte The Gossip Project</h2>
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <%= label_tag 'Email :' %>
  <%= email_field 'email', params[:email], class: "form-control" %>
  <br />
  <br />
  <%= label_tag 'Prénom :' %>
  <%= text_field_tag 'first_name', params[:first_name], class: "form-control" %>
  <br />
  <br />
  <%= label_tag 'Nom de famille :' %>
  <%= text_field_tag 'last_name', params[:last_name], class: "form-control" %>
  <br />
  <br />
  <%= label_tag 'Age :' %>
  <%= number_field 'age', params[:age], class: "form-control",  in: 7..99 %>
  <br />
  <br />
  <%= label_tag 'Description :' %>
  <%= text_area_tag 'description', params[:description], class: "form-control", in: 10..100 %>
  <br />
  <br />
  <%= label_tag 'Mot de passe :' %>
  <%= password_field_tag 'password', params[:password], class: "form-control" %>
  <br />
  <br />
  <%= submit_tag "S'inscrire sur The Gossip Project !", class: "btn btn-primary" %> 
<% end %>

<% if @user.errors.any? %>
  <p style="padding-top: 2rem;">L'inscription a échouée pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= flash[:alert] = message %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<h2 style="margin-bottom: 2rem;">Page utilisateur</h2>
 

<div>
  <h5>Prénom :</h5>
  <p><%= @user.first_name %> </p>
  <h5>Nom :</h5>
  <p><%= @user.last_name %> </p>
  <h5>Description :</h5>
   <p><%= @user.description %> </p>
  <h5>Email :</h5>
  <p><%= @user.email %> </p>
  <h5>Age :</h5>
  <p> <%= @user.age %>  </p>
  <h5>Ville :</h5>
  <p> <%= @user.city.name %>  </p>
</div>