config/routes.rb
Rails.application.routes.draw do
  
  root to:'static_pages#home', as: 'home'

  resources :gossips
  resources :users
  resources :cities, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'static_pages/team', to: 'static_pages#team'
  get 'static_pages/contact', to: 'static_pages#contact'
  get 'welcome/:name', to: 'static_pages#welcome'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :tags_assignments
  has_many :tags, through: :tag_assignments
  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_assignments, dependent: :destroy
  has_many :gossips, through: :tag_assignments
end

app/models/tag_assignment.rb
class TagAssignment < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email,
    presence: true,
    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    # Look up the current user based on user_id in the session cookie:
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'Vous devez être connecté pour voir cette page.' if current_user.nil?
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @users = User.where(city_id: @city.id)
    @gossips = Gossip.where(user_id: @users)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :show]

  def new
    @gossip = Gossip.new
  end

  def index
    @gossips = Gossip.all
  end

  def create
    @gossip = Gossip.new('title' => params[:title], 'content' => params[:content], user_id: current_user[:id])
    if @gossip.save
      flash[:notice] = "Potin enregistré !"
      redirect_to home_path
    else
      flash[:alert] = "Erreur, le potin n'a pas été enregistré"
      puts @gossip.errors.messages
      render 'new'
    end
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user.id
      @gossip = Gossip.find(params[:id])
    else
      redirect_to(gossip_path(params[:id]), notice: "Tu dois en être l'auteur du potin !")
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user.id
      @gossip = Gossip.find(params[:id])
      if @gossip.update(title: params[:title], content: params[:content])
        redirect_to(home_path, notice: 'Gossip modifié!')
      else
        render :edit
      end
    else
     redirect_to(gossip_path(params[:id]), notice: "Tu dois en être l'auteur du potin !")
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user.id
      @gossip = Gossip.find(params[:id])
      @gossip.destroy
      redirect_to(home_path, notice: 'Gossip supprimé!')
    else
      redirect_to(gossip_path(params[:id]), notice: "Tu dois en être l'auteur du potin !")
    end
  end

  def authenticate_user
    unless current_user
      redirect_to(new_session_path, notice: 'Vous devez être connecté')
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    puts user
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: "Connecté!"
    else
      flash.now[:alert] = "Email / Mot de passe invalide"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(
      email: params[:email],
      password: params[:password],
      city_id: 1,
      description: params[:description],
      age: params[:age],
      first_name: params[:first_name],
      last_name: params[:last_name]
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Utilisateur enregistré !"
      redirect_to home_path
    else
      flash[:alert] = "Erreur dans l'inscription"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Accueil <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/static_pages/team">L'équipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href='<%= new_gossip_path %>' >Créer un gossip</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/static_pages/contact">Contact</a>
          </li>
          <% if current_user == nil %>
            <li class="nav-item dropdown navbar-right">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Inscription/Connection
              </a>
             <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
               <a class="dropdown-item"><%= link_to 'Se connecter', login_path %></a>
               <a class="dropdown-item"><%= link_to "S'incrire", new_user_path %></a>
              </div>
              </li>            
          <% else %>
          <li class="nav-item navbar-right">
            <a class="nav-link"> <%= "Connecté en tant que : #{current_user.email}" %></a>  
          </li>             
          <li class="nav-item navbar-right ">
            <a class="nav-link"><%= link_to 'Se déconnecter', logout_path, method: :delete %></a>
          </li>
          <% end %>     
        </ul>
        
      </div>
    </nav>
    
    <% if notice %>
      <%= notice %>
    <% end %>
    <% if alert %>
      <%= alert %>
    <% end %>
    <div class="container" style="padding-top: 5rem;">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>